import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import ThemeContextProvider from "@/context/theme-context";
import { DivisionContextProvider } from "@/context/ContextProvider";


export const metadata: Metadata = {
  title: "Medfuture Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className="bg-white text-gray-950 dark:bg-blue-800  dark:text-gray-50 dark:text-opacity-90">
        <ThemeContextProvider>
          <DivisionContextProvider>
            <Navbar />
            {children}
            <Footer />
          </DivisionContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
